### ISSUE TITLE
error: expected scalar type Half but found BFloat16

### ISSUE THREAD

**Issue by ClothingAI** [sipie800/ComfyUI-PuLID-Flux-Enhanced#5]
I keep getting this error. and the workflow stops At the sampler custom advanced:
![image](https://github.com/user-attachments/assets/e5e2cdbb-7825-4f3c-8d1c-e7bd6e869d1d)

I dont understand what todo:
- I treid changing samples
- - I tried changing loader for flux models (took unet..)

![image](https://github.com/user-attachments/assets/46a27b3e-6d58-4e28-b724-6440804dcd6b)
 
What is the problem?

**Comment by sipie800** [comment]
I can't see your error message. From my experience, the problem is not about sampler. your unet loader with gguf may be the issue. please try feed back to the gguf loader node. 
If the thing is not about node, do you use some GPU which does not support bfloat16 ?

**Comment by ClothingAI** [comment]
Quadro 6000, does that not support it? If no, what to do then?
It has 24G vRAM

**Comment by sipie800** [comment]
bf16 is supported with at least compute capability 8.0, quandro 6000 may be 7.5. I'm not quite an expert about these things. you need to use fp16 checkpoint of flux as long as the regular unet loader node.

**Comment by ClothingAI** [comment]
could not even make a regular flux pulid workflow work, can you suggest me a json with fp16 please? with precise name of models so I have no doubt no error

**Comment by sipie800** [comment]
may try [pulid_flux_16bit_simple.json](https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/blob/main/examples/pulid_flux_16bit_simple.json)

**Comment by ClothingAI** [comment]
> may try [pulid_flux_16bit_simple.json](https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/blob/main/examples/pulid_flux_16bit_simple.json). Be aware that it's may consume more VRAM. You can just grab and use a fp8 checkpoint of flux dev in the fp16 workflow, it's more feasible.

Thanks! I have enough VRAM it seems:
![image](https://github.com/user-attachments/assets/25ff73f5-43b8-4511-94bf-efae757cbf42)

But I just keep getting a specific error apparently:
https://github.com/balazik/ComfyUI-PuLID-Flux/issues/33#issuecomment-2434144823

**Comment by ClothingAI** [comment]
Even this:
![image](https://github.com/user-attachments/assets/6469b31a-eac6-41c1-a5f4-2d64fdb86ace)
