### ISSUE TITLE
might be a bug with "weight" aplly 

### ISSUE THREAD

**Issue by sd2530615** [sipie800/ComfyUI-PuLID-Flux-Enhanced#6]
i aplly two pulid on first stage of generating picture,and the 2nd one on highresFix stage. they had diferenet weight like 0.35,0.85

but when i generating the 2nd,3rd picture, the weight of first Pulid seems up to 1(or 0.85?) itself,lowring the first pulid weight to 0 didnts fix it.

**Comment by sipie800** [comment]
i'm not sure if it supports multi node in one  workflow，the origin node just may not support. you can try deleting and then re-adding the pulid nodes in your workflow

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/23/2024 13:50 |
| To | sipie800/ComfyUI-PuLID-Flux-Enhanced ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [sipie800/ComfyUI-PuLID-Flux-Enhanced] might be a bug with "weight" aplly (Issue #6) |

i aplly two pulid on first stage of generating picture,and the 2nd one on highresFix stage. they had diferenet weight like 0.35,0.85

but when i generating the 2nd,3rd picture, the weight of first Pulid seems up to 1(or 0.85?) itself,lowring the first pulid weight to 0 didnts fix it.

**Comment by sd2530615** [comment]
i disable the enhanced node ,it bug in original ComfyUI-PuLID-Flux node too, i guess it's some bug that brings to your node,sorry to bother you ,ill post this issue to that node
